from dotenv import load_dotenv
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_huggingface import ChatHuggingFace, HuggingFaceEndpoint

load_dotenv()

# Define the model
llm = HuggingFaceEndpoint(repo_id="google/gemma-4-31B-it", task="text-generation")

model = ChatHuggingFace(llm=llm)

parser = JsonOutputParser()

template = PromptTemplate(
    template="Give me name of an anime character with his/her origin \n {formal_instruction}",
    input_variables=[],
    partial_variables={"formal_instruction": parser.get_format_instructions()},
)

# prompt = template.format()

# this returns a JSON object
# print(prompt)

# response = model.invoke(prompt)
# print(response)

# responseInJSON = parser.parse(response.content)
# print(responseInJSON)

# Or, getting the same output with chains
chain = template | model | parser
response = chain.invoke({})
print(response)

# limitation with json output_parsers :
# the json schema cannot be designed by our own will, it is automatically generated by the llm

# template = PromptTemplate(
#     template="Give me 5 facts about {topic} \n {format_instruction}",
#     input_variables=["topic"],
#     partial_variables={"format_instruction": parser.get_format_instructions()},
# )

# chain = template | model | parser
#
# result = chain.invoke({"topic": "black hole"})
#
# print(result)
